# Generated by Django 2.0.7 on 2019-11-23 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20191123_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Topic'),
        ),
    ]
